### ISSUE TITLE
Installing ember-cli-simple-auth breaks Ember in mobile Safari

### ISSUE THREAD

**Issue by bravo585** [simplabs/ember-cli-simple-auth#38]
For some reason, simply installing ember-cli-simple-auth breaks Ember in Safari (testing on iOS 8.4). Here's a bare-bones example which reproduces the problem:
```
> ember new test-foo
> cd test-foo
> ember generate controller application
```

```
// app/templates/application.hbs
<h2 id="title">Welcome to Ember.js</h2>
<a {{action "foo"}} style="cursor:pointer">CLICK ME {{name}}</a>
{{outlet}}
```

```
// app/controllers/application.js
import Ember from 'ember';

export default Ember.Controller.extend({
  actions: {
    foo: function() {
      this.set('name', 'foo');
    }
  }
});
```

If you open this page in Safari on your iPhone, you'll see "foo" when you click "CLICK ME". Now install ember-cli-simple-auth:

```
> ember install ember-cli-simple-auth
```

Reload in Safari, and you'll see clicking "CLICK ME" doesnt do anything.

**Comment by pmelnichuk** [comment]
I was wondering why my web app wasn't working on my mobile phone. I believe I am encountering the same issue.

**Comment by marcoow** [comment]
Would be great if someone could remote-debug this and see whether there's any error.

**Comment by krivaten** [comment]
Are you trying to sign in from a _private_ tab?

We've had a few clients reporting the same issue on an inconsistent variety of iPhones, so I went and visited one of them and noticed it he was trying to sign in from within a _private_ tab. 

When I did the same on my iPhone and even in Safari on my laptop, I was unable to log in. When I checked the console, I saw `setItem@[native code]...`.

**Comment by fsmanuel** [comment]
The problem with private mode on safari is that it has no `localStorage`. The crazy thing about it that it exposes `localStorage` but fails if you try to `setItem`.

**Comment by bravo585** [comment]
Yes now that I'm testing it, this is only a problem for Safari in private mode.

**Comment by pmelnichuk** [comment]
It's quite funny indeed that you can read local storage but not set it. What seems to make the most sense is to clear the localStorage when the private tab is closed. But hey, i'm not an apple PM.

http://www.jstorage.info/ I'm contemplating forking off master and just swapping in jstorage in for the default localStorage calls.

**Comment by marcoow** [comment]
Can the error that Safari Mobile raises when trying to set a key in the localStorage in private mode somehow be identified? In that case the adapter could handle it and simply log a warning. I also wonder whether there are other browsers that show the same or similar behavior and how cookies are treated in browser's private modes.

**Comment by fsmanuel** [comment]
The error is:
```
DOMException
code: 22
message: "QuotaExceededError: DOM Exception 22"
name: "QuotaExceededError"
```

**Comment by pmelnichuk** [comment]
It appears as though many clients other are experiencing the same problem. Apparently it occurs on private browsing on the mac safari as well. The exception raised:
QUOTA_EXCEEDED_ERR: DOM Exception 22

The general consensus is that the implementation of localStorage is a little funny. You can read data, but, cannot write data. Very different from how the cookie handling works.

The problem with using cookies is that one would be opening themselves up to CSRF attacks in certain situations.

There are potentially some other solutions that might work, but, I have not had the opportunity to test them yet. IndexDB, jstorage .. a few others: http://www.saintsatplay.com/blog/2014/06/browser-data-storage-options-for-the-frontend-developer#.VeALPNNVikp

**Comment by marcoow** [comment]
`DOMException` - wow; it's amazing how fundamentally broken JS errors are.

**Comment by fsmanuel** [comment]
hehe. i guess something like
```
ENV['simple-auth'] = {
  storeFallbacks: ['cookie', 'ephemeral']
}
```
could be implemented. I can open a PR to with a modified version of [tryStorage](https://github.com/funkensturm/ember-local-storage/blob/master/addon/helpers/storage.js).

**Comment by marcoow** [comment]
I think it makes more sense to configure the session store dynamically (or change the config in an initializer when private mode is detected) - I don't really think this is really necessary to be included in the library itself.

**Comment by fsmanuel** [comment]
That's true. Maybe a helper/util would be good that people can use to detect if `localStorage` is available.

**Comment by marcoow** [comment]
Yeah but that would for sure not belong into ESA.

**Comment by janwerkhoven** [comment]
+1 experiencing same, solution needed

**Comment by pmelnichuk** [comment]
just use cookie as the local store instead of localstorage

**Comment by janwerkhoven** [comment]
How?

**Comment by pmelnichuk** [comment]
```
 ENV['simple-auth'] = {
    store: 'simple-auth-session-store:cookie',
  };
```

**Comment by janwerkhoven** [comment]
Thanks @pmelnichuk for the tip putting me on the right track.

What fixed this issue for me was:

1. First install the Ember CLI addon: [ember-cli-simple-auth-cookie-store](https://github.com/simplabs/ember-cli-simple-auth-cookie-store)
2. Then add the following to `config/environment.js`:

```
  var ENV = {

    ....

    'simple-auth': {
      store: 'simple-auth-session-store:cookie'
      // store: 'simple-auth-session-store:local-storage' // breaks in safari private mode (JW)
    },

    'simple-auth-cookie-store': {
      cookieName: 'user-session'
    }

  };
```

Works
 :+1:

**Comment by janwerkhoven** [comment]
Also mind that more people than you think read these issues. It's not just a 1 on 1.
Adding code examples and solutions will definitely help others too :)

**Comment by marcoow** [comment]
Closing this as it isn't actually a bug. The application has to define a different store than the `localStorage` store when no `localStorage` is available. It might be a good idea to implement a store that transparently falls back from `localStorage` to cookies etc. in the future but that's another story.

**Comment by janwerkhoven** [comment]
@marcoow Agreed, ideally we use localstorage everywhere. Now because of Safari we have to force cookies everywhere. Fallback would be sweet.

**Comment by erwamartin** [comment]
@janwerkhoven @marcoow I had the same issue yesterday and I created an initializer to change the store configuration only when you use the Private Browsing on Safari (or any browser which don't have localStorage enabled):

```
// initializers/custom-store.js
import config from '../config/environment';
export default {
  name: 'custom-store',
  before: 'simple-auth',
  initialize: function() {
    try {
        localStorage.setItem('test', '1');
        localStorage.removeItem('test');
    } catch (error) {
        config['simple-auth'].store = 'simple-auth-session-store:cookie';
    }
  }
};
```


```
// config/environment.js
  var ENV = {
    ....
    'simple-auth': {
      store: 'simple-auth-session-store:local-storage'
    },
    'simple-auth-cookie-store': {
      cookieName: 'user-session'
    }
  };
```

Not sure it's the best way to do that, but it works :)

**Comment by janwerkhoven** [comment]
@erwamartin Awesome, fallback works! Thanks so much :smile:

**Comment by Fryie** [comment]
This should be fixed with ember-simple-auth 1.0 and the default store adapter, I believe?

**Comment by marcoow** [comment]
@Fryie: yes, this is fixed by the [new adaptive session store](http://ember-simple-auth.com/api/classes/AdaptiveStore.html).

**Comment by JonathanJesse** [comment]
The colossal monetary influence which [best essay services review (http://bestessayservicesreviews.blogspot.com/) learning has given made two classes of individuals – rich and poor. This has realized misuse of the poor by the rich. Learning has given man another sort of force fit as a fiddle of dangerous weapons. The two Great Wars of the most recent century have taught man that the weapons put away in man's armory can transform this lovely world into a cemetery.

**Comment by ghost** [comment]
Is this broken again? For some reason my app is throwing this error in mobile safari when using private browsing mode. I tried to explicitly set the 'adaptive' store, but I still receive the `DomException` error. It seems to happen in the `session.authenticate('authenticator:slack')` call.

**Comment by marcoow** [comment]
ember-cli-simple-auth has been deprecated. Please check https://github.com/simplabs/ember-simple-auth
